### ISSUE TITLE
Transcription-app crashes on optimization

### ISSUE THREAD

**Issue by LJRoffler** [cmm-21/a6#1]
Hi every one

I am having issues with transcription-app. I have not changed the optimization function yet at the moment O=0 always.
Everytime I try to run the optimization, the app crashes immediately and an exception is throw , something like

Exception thrown at 0x00007FF7D0589704 in transcription-app.exe: 0xC0000005: Access violation reading location 0x000000004900420B

I have tried to run the optimization with stepPhysicsExplicitEuler implemented and with out it and it still always crashes.
In my opinion the app should not crash, even if O is always 0.

Is anyone else having this issue? Or is my assumption wrong?

**Comment by MiguelZamoraM** [comment]
Hi. 

Could you please give some details on the platform you are using to run things?
Also, have you tried running things on debug mode to see where it crashes?

**Comment by LJRoffler** [comment]
I am running it on Windows with Visual Studios 2019.
I can try running it in debug mode.

**Comment by LJRoffler** [comment]
It crashes in SparseLU.h on line 220
eigen_assert(m_factorizationIsOk && "The matrix should be factorized first");

**Comment by MiguelZamoraM** [comment]
I was able to replicate your problem. So, for the transcription-app we have SECOND_ORDER_SOLVER = true by default.

If you have not implemented the objective, then when the Newton solver tries compute the seach direction, it will throw an error when computing the inverse of the Hessian.

https://github.com/cmm-21/a6/blob/7428ad8b8481f9b1a42b793992173f0adee9db67/src/optLib/NewtonFunctionMinimizer.h#L20

I would say this is kind of the expected behavior. Try implementing an objective and let me know if you still face problems once the objective is not zero all the time.

**Comment by LJRoffler** [comment]
I tried one that was always 50, as well as the objective function from direct shooting and one that I actually thought might be correct and it still had the same behaviour. But maybe I'm just not at all on the right track for O.

**Comment by LJRoffler** [comment]
It appears I was just very off track. Sorry for the false alarm and thank you so much for your time!

**Comment by MiguelZamoraM** [comment]
Just to clarify, the problem with having an objective that is always constant is that the gradient will be zero and the hessian will be zero as well. So, when computing the search direction things will crash. Something similar happens when you use an objective that is linear. The gradient will be constant and the hessian will be zero again, leading to a crash.

**Comment by luohwu** [comment]
Hi Miguel,
I have some trouble with task 8. So no matter what the objective function is, the final objective value is always constant. I only implemented the evaluate function. Do I miss something that I should implement?   I have check everything but failed to find the problem.
