### ISSUE TITLE
Task 8: optimizing runs slow despite release mode and parameter tuning crashes

### ISSUE THREAD

**Issue by iqiac** [cmm-21/a6#10]
I'm trying to find a good objective function for the transaction app. When I start the app in release mode and check optimize, it runs quite slow. Also the app to crashes when certain coefficients get beyond some threshold it seems.

I just have one loop and penalize the deviations. The app doesn't crash from the beginning.
What could be the problem?
I've pushed my code, for the case it's needed.

**Comment by MiguelZamoraM** [comment]
I suspect you have a similar problem as the one in issue https://github.com/cmm-21/a6/issues/1 . Most likely the app is crashing because computing the inverse of the hessian fails due to bad conditioning of the objective. After taking a brief look at your code I also noticed that you use .norm() in some places for the objective, but when using Newton's method I would recommend squaredNorm() instead.  Give it a try and let me know how it goes.

**Comment by iqiac** [comment]
Thanks very much. It seems to work now. I fixed the parameters for the most terms. It's strange that I can optimize and then tune the coefficient for the regularizer (log_c_reg) to the mininimum, but if I optimize with the coefficient already set to min, it crashes. It also crashes if I drag the x' position too fast, then it explodes and crashes.

Edit: had to find the suitable coefficients, now it shouldn't anymore

**Comment by nwicki** [comment]
@iqiac: What coefficients did you adjust and what was actually the problem? Did it look similar to my issue described in #28 ? I don't see in what way one should adjust the coefficients and why it would help. Any clarification is appreciated :)

**Comment by MiguelZamoraM** [comment]
@nwicki This thread  https://github.com/cmm-21/a6/issues/24, specially https://github.com/cmm-21/a6/issues/24#issuecomment-847597023 and https://github.com/cmm-21/a6/issues/24#issuecomment-848533633 might help you understand why adjusting coefficients might help. 

But in short the app is probably crashing because it fails to compute a search direction, because that involves computing the inverse of the hessian,  which can fail when the hessian is ill conditioned.

All that might happen when you have very large states or controls and that's why adding some regularization terms might help.
