### ISSUE TITLE
Task 10 approach

### ISSUE THREAD

**Issue by iqiac** [cmm-21/a6#13]
Hello

For the challenge-app, I just found out (through tuning) and hardcoded the suitable velocity s.t. the spaceship orbits on the circle. Is this actually acceptable or is some fancy formula required for this task (incl. description in readme)?

Thanks in advance.

**Comment by MiguelZamoraM** [comment]
I don't fully understand what you mean when you say you found/hardcoded a suitable velocity.  However, as this a trajectory optimization assignment, you need to use the basic tools you saw during the lecture. It might be best if you push your code so that I can have a better understanding of how you are attempting to solve the problem.

**Comment by iqiac** [comment]
I mean I just assign the velocity directly, e.g. to [-2, -4]^T (this is not the actual velocity I took) and the spaceship orbits on the circle. I didn't use any formula to get this velocity.

I also pushed the code.

**Comment by MiguelZamoraM** [comment]
You are not assigning the velocity directly! What you are doing is setting a target velocity in your objective and you penalize deviations from such target velocity but in the end you are still solving a trajectory optimization problem and that is completely fine.

**Comment by iqiac** [comment]
> You are not assigning the velocity directly! What you are doing is setting a target velocity in your objective and you penalize deviations from such target velocity.

Ah yeah you are correct. I formulated it wrong, sorry for the inconvenience. Thanks very much.
