### ISSUE TITLE
Task 8 - app crashes

### ISSUE THREAD

**Issue by lauratissari** [cmm-21/a6#17]
Hi Miguel

We saw the other issues about task 8 about the crashing app, we tried to consider the hints you provided there, but we still could not manage running the app.
We tried printing the objective function, it should not be constant, but as the app crashes we are not sure about it.
Can you help us getting back on the right track?

Cheers

**Comment by MiguelZamoraM** [comment]
Double check the way in which you are penalizing deviations from a physical trajectory.  Remember to initialize all your variables and I think  there's a loop where you are not actually accumulating some values.

**Comment by MiguelZamoraM** [comment]
Also try to have different weights/coefficients for different parts of your objective. So one coefficient to "enforce"  initial conditions, then a different one to penalize deviations from a physical trajectory and so on.  Start with a value of 1 and then try to tune things.

**Comment by lauratissari** [comment]
Thanks for the quick reply, thank you for the hint about the the non accumulating loop. Can you elaborate on the phrase "double check the way in which you are penalizing deviations from a physical trajectory."? We are not sure what you mean by that, because we think we implemented the soft constraint according to equation (3).

**Comment by MiguelZamoraM** [comment]
I guess the comment about double checking the way in which you penalize deviations from physics and the non accumulating loop was the same.  By the way, this hint  ( https://github.com/cmm-21/a6/issues/15#issuecomment-845963602) might also be useful for you.

**Comment by lauratissari** [comment]
Hi Miguel, I still cannot find the mistake, that causes the app to crash constantly. I tried regularizing everything and weighting them with different parameter magnitudes but nothing seems to work.  Do you think the regularizes or the weights are the cause for the app to crash?
I don't know how to debug the problem, as the app is crashing constantly.

**Comment by MiguelZamoraM** [comment]
In the last loop, where you regularize everything, you are missing the last time step. It should be `for (int k=0; k<=K; k++) ` Just by doing that the app does not crash. I would also encourage you to change the coefficients of the objective using the GUI, Otherwise, you have to recompile every time you want to change them.

**Comment by lauratissari** [comment]
Oh I had misunderstood the count of x0 and v0. Thank you very much for the help.

**Comment by hugorilla** [comment]
I'm in a very similar position. I've been trying all evening to modify the weights (for initial conditions, physics, and regularization) in my objective function so that the app doesn't crash, but I've had no luck (with any combination of small/large starting values). By printing out the values of `O` after each call to `evaluate()`, I can see that the optimizer is not modifying the optimization variables - i.e. it is not finding a direction of improvement - between function calls. I'm quite sure that I've accounted for all the optimization variables in my objective function, and I have included (I believe) all the constraints listed in Question 8. I would try the small adjustments recommended in other issue threads, but I can't get a single optimization working with the Newton method. Can you offer any advice on how I can continue to debug?

**Comment by MiguelZamoraM** [comment]
Hi @hugorilla . 

- Do not print the objective inside the evaluate function. That function is called many times to evaluate the gradients and the hessian via finite differences. Use checkboxes in the GUI "PRINT O" and "PRINT "|G|" to print the value of the objective correctly.  

- After a brief look at your code, I think you are on the right track. Just consider adding a separate coefficient for the initial conditions to your GUI such that you can tune that as well and  follow the advice in https://github.com/cmm-21/a6/issues/17#issuecomment-845992570 to initialize the coefficients to 1 or the log_c_coefficient = 0 and start tuning from there. With that you should be good.

**Comment by MiguelZamoraM** [comment]
I think I meant final target. Add coefficient for the final target to the GUI.

**Comment by hugorilla** [comment]
@MiguelZamoraM, thank you for your helpful response to my last-minute question - it was very helpful! 😄
