### ISSUE TITLE
Q. 4 what indicates solution works well?

### ISSUE THREAD

**Issue by Glanfaloth** [cmm-21/a6#6]
Should I tune the parameters according to eye observation (spaceship stops exactly at the purple dot) or according to how close O is to zero? What is good final O?

**Comment by MiguelZamoraM** [comment]
It is difficult to say what a good final value for the objective O should be, since that depends on the kind of objective you use. In general what you are looking for is to get the 2-norm of the objective's gradient  as close to zero as possible. 

For this introductory problem, I would say that tuning the parameters according to the behavior you observe should yield similar results to monitoring the norm of the gradient, but to start building good practices I would encourage you to show on your gui the 
gradient's norm as you optimize. (Doesn't have to be a plot, just displaying the value should help you)
